### ISSUE TITLE
Fel vid skapning av badplats

### ISSUE THREAD

**Issue by jh222xk** [jwilsson/1DV450_jw222eu#19]
Om man försöker skapa en badplats och trycker på kartan så får man:

`TypeError: Cannot read property '$$hashKey' of undefined
    at Object.w [as extend] (angular.js:406)
    at app.min.js:244
    at l.$get.l.$broadcast (angular.js:14720)
    at app.min.js:2682
    at l.$get.l.$eval (angular.js:14401)
    at l.$get.l.$apply (angular.js:14500)
    at angular.module.factory.safeApply (app.min.js:4229)
    at Object.angular.module.factory.genDispatchMapEvent (app.min.js:2676)
    at L.Mixin.Events.fireEvent (script.min.js:473)
    at L.Map.L.Class.extend._fireMouseEvent (script.min.js:2224)`

och om man sedan klickar på "Spara" så får man följande fel:

`5angular.js:11607 TypeError: Cannot read property 'lat' of undefined
    at l.app.controller.$scope.saveLocation (http://188.166.45.232:8080/assets/js/app.min.js:225:59)
    at ib.functionCall (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:198:303)
    at Dc.(anonymous function).compile.d.on.f (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:214:485)
    at l.$get.l.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:125:305)
    at l.$get.l.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:126:6)
    at HTMLFormElement.<anonymous> (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:215:36)
    at HTMLFormElement.c (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:32:389)`

Om man sedan uppdaterar sidan (http://188.166.45.232:8080/#/locations/create) så får man upp:
`GET http://188.166.45.232:8080/app/locations/views/locations-form.html 500 (Internal Server Error)`

**Comment by jwilsson** [comment]
Jag lyckas inte återskapa felet, varken på http://188.166.45.232:8080/ eller när jag drar ner det lokalt. 

Vilken browser kör du?

**Comment by jh222xk** [comment]
Google Chrome kör jag på OSX.

**Comment by jwilsson** [comment]
Skumt, precis samma browser som jag kör.

Du har inte möjlighet att testa igen? Så ska jag kolla vidare och se om jag kan lyckas återskapa problemet.

**Comment by jh222xk** [comment]
Jag ber om ursäkt, felet beror på att jag hade nekat geolocation men jag tycker dock ändå att man ska kunna skapa en badplats även om jag inte godkänt geolocation.

**Comment by jwilsson** [comment]
Aha, tack för infon!

Då ska jag lägga in en koll för det.
